name: ci-java-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['8', '11']
    name: Java ${{ matrix.jaav }} version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - run: gradle test
      - run: gradle run
